[project]
name        = "spectronote"
description = "🎧 Piano-perfect audio spectrogram"
version     = "0.10.0"
license     = "AGPL-3.0"
readme      = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "attrs",
    "cyclopts",
    "dearlog",
    "shaderflow",
]

[project.urls]
GitHub = "https://github.com/BrokenSource/SpectroNote"

[project.scripts]
spectronote = "spectronote.__main__:main"
spectro     = "spectronote.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
